name: vox_finance
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1

  path_provider: ^2.1.0
  intl: ^0.19.0
  fl_chart: ^0.69.0
  speech_to_text: ^7.3.0
  image_picker: ^1.1.0
  google_mlkit_text_recognition: ^0.15.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/vox_icon.png"