name: vox_finance
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2

  crypto: ^3.0.3
  cupertino_icons: ^1.0.8

  firebase_storage: ^12.3.4
  file_picker: ^8.3.7
  share_plus: ^7.2.1

  # ================================
  # BANCO DE DADOS — SQFLITE
  # ================================
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0

  # ================================
  # FIREBASE
  # ================================
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.12

  # ================================
  # OUTRAS DEPENDÊNCIAS
  # ================================
  intl: ^0.19.0
  fl_chart: ^0.69.0
  speech_to_text: ^7.3.0
  image_picker: ^1.1.0
  google_mlkit_text_recognition: ^0.15.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.2
  flutter_native_splash: ^2.4.7
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/google_signin.png
    - assets/splash_vox.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/vox_icon.png"

# ===========================================
#   CONFIGURAÇÃO DO SPLASH — AJUSTADO
# ===========================================
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_vox.png
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/splash_vox.png
